### PR TITLE
update patch and remove entry from file list

### PR DESCRIPTION
**Pull request by thomasinaz41213**
Removed number of digital inputs limit.  Remove services.json entry from fileListPatched. Patching of this file is handled by arguments in the setup script based on the large os being installed. Having this file in the fileListPatched will result in an attempt to install the patch ALWAYS regardless of OS image, which will result in a failed install on non large os systems. Also breaks uninstall of services.json patch when package is uninstalled.

v3.1 uninstall breaks services.json unpatching because of the entry in the filelist. Shouldn't be an issue if v3.1 was never uninstalled, but if you did uninstall v3.1 you will most likely get a no fileset error when trying to reinstall again. if so, just run the following from terminal on the cerbo. Copy and paste it all at once.

patch -R /usr/lib/node_modules/@victronenergy/node-red-contrib-victron/src/services/services.json /data/RemoteGPIO/FileSets/PatchSource/services.json.patch

### CODE REVIEW

**Comment by Lucifer06** [comment]
Thx Thomas,

Have merged it.
During cmd line base installation, I see the following error message:
patching file ***@***.***/node-red-contrib-victron/src/services/services.json
Possibly reversed hunk 1 at 6822
Hunk 1 FAILED 3848/3848.
         "type": "enum",
         "name": "Venus relay 4 state",

But It seems the file is correctly patched anyway.
I made sure before executing the setup, that I restored an original service.json
Any idea?


Sorry for asking, but I don’t yet understand how the patch is working. I have identified you specify the line after the @, but what is the second argument?

Ceers,
FreD.
------------------------------------------------------------------------------
The water is always bluer on the other side of the ocean ;-)

**Comment by thomasinaz41213** [comment]
What version OS? Did you replace the services.json with the original untouched one from the Venus image?

The entry in the patch files that have @@ tell the patch mechanism where to look for the original code, compares it to the few lines surrounding where the patch should get applied, and if there is a match it inserts/removes the appropriate text. Because of this it's very important when creating the patch files that a virgin untouched file be used as the .source (more on that below), and that an exact copy of the source be used to create the .edited file, making changes to the desired text/area of the file only.

.patch files are created using 'diff -u file.source file.edited > file.patch'

Patch only looks at specific sections of the file where the hunks should be added or removed, and ignores the rest. That makes it a great tool for version independency, but  also requires that the .edited files are created in a very specific way. I always open and verify the patch file in a code editor to make sure the diff didn't explode and just replace the whole file.

**Comment by thomasinaz41213** [comment]
I have installed and uninstalled v3.1.2 on os 3.22 and 3.30-18 from command line with no errors and services.json patched correctly. Unless you are running a beta os services.json does not have 6800 lines even with the patch installed. The error you posted indicates hunk 1 failed which means the patch does not get applied. Since you say the patch was applied I believe that services.json was left in a patched state because of a previous issue from v3.1 and that will cause what you experienced. 

I would uninstall RemoteGPIO and do a fresh firmware install. Or download and extract the Venus image and replace /usr/lib/node_modules/@victronenergy/node-red-contrib-victron/src/services/services.json

**Comment by Lucifer06** [comment]
I was running v3.22 of Venus OS. And I did manually restored the service.json original file. Then after patch applied with this error, I was surprised to see a correct patched service.jsonMaybe my restore of the service.json was not correct, not sure. I will test again laterThxExcuse possible typo: swallowed by my iPhoneLe 18 mars 2024 à 15:19, thomasinaz41213 ***@***.***> a écrit :﻿
I have installed and uninstalled v3.1.2 on os 3.22 and 3.30-18 from command line with no errors and services.json patched correctly. Unless you are running a beta os services.json does not have 6800 lines even with the patch installed. The error you posted indicates hunk 1 failed which means the patch does not get applied. Since you say the patch was applied I believe that services.json was left in a patched state because of a previous issue from v3.1 and that will cause what you experienced.
I would uninstall RemoteGPIO and do a fresh firmware install. Or download and extract the Venus image and replace ***@***.***/node-red-contrib-victron/src/services/services.json

**Comment by thomasinaz41213** [comment]
You uninstalled the package before you restored services.json? And you remembered to use force when copying the file? Just throwing out ideas here. You know more about this programming stuff than I do.

**Pull request merged**
