### PR TITLE
rebuild package to use patch and some other enhancements

### PR DESCRIPTION
**Pull request by thomasinaz41213**
1. removed version specific fileset dependencies and replaced with patch files.
(should be backward compatible. I will do further testing to determine how far back we can go)
2. added current version of helper resources to achieve the following...
3. cleaned up setup script by removing updateactivefile and restoreactivefile entries. (now done automatically)
4. cleaned up setup script by removing DbusSettings installation lines. (now done automatically)
5. RemoteGPIO settings now survive uninstall/reinstall
6. removed some files no longer being used
7. setup script now runs faster

### CODE REVIEW

**Comment by Lucifer06** [comment]
Thx.D-Bus settings are automatically installed: really? Carrefull with that because I can imagine the ones related with relays and digital inputs could be automatically installed but I doubt it will do the ones specific for RemoteGPIO (such as the ones essential for the configuration, the watchdog, the services). Excuse possible typo: swallowed by my iPhoneLe 16 mars 2024 à 20:34, thomasinaz41213 ***@***.***> a écrit :﻿
removed version specific fileset dependencies and replaced with patch files.
(should be backward compatible. I will do further testing to determine how far back we can go)
added current version of helper resources to achieve the following...
cleaned up setup script by removing updateactivefile and restoreactivefile entries. (now done automatically)
cleaned up setup script by removing DbusSettings installation lines. (now done automatically)
RemoteGPIO settings now survive uninstall/reinstall
removed some files no longer being used
setup script now runs faster




You can view, comment on, or merge this pull request online at:
  https://github.com/Lucifer06/RemoteGPIO/pull/20

Commit Summary

  0cdf755  Create synctest
  5abb8d3  sync
  7014dd0  Squashed commit of the following:
  e110fd6  Squashed commit of the following:
  e39f670  Delete services.json.patchfile
  ac82b76  Squashed commit of the following:
  e60daf2  cleanup for pull request


File Changes  (44 files)

  
    A
    DbusSettingsList
    (12)
  
  
    A
    FileSets/PatchSource/PageSettingsIo.qml.patch
    (183)
  
  
    A
    FileSets/PatchSource/gpio_list.patch
    (43)
  
  
    A
    FileSets/PatchSource/relaystate.py.patch
    (34)
  
  
    A
    FileSets/PatchSource/serial-starter.rules.patch
    (41)
  
  
    A
    FileSets/PatchSource/services.json.patch
    (294)
  
  
    D
    FileSets/fileList
    (5)
  
  
    A
    FileSets/fileListPatched
    (4)
  
  
    D
    FileSets/v3.21/COMPLETE
    (1)
  
  
    D
    FileSets/v3.21/OverviewRelays.qml
    (204)
  
  
    D
    FileSets/v3.21/OverviewRelays2.qml
    (204)
  
  
    D
    FileSets/v3.21/OverviewRelays3.qml
    (204)
  
  
    D
    FileSets/v3.21/PageSettingsRelay.qml
    (532)
  
  
    D
    FileSets/v3.21/RemoteGPIO.json
    (3298)
  
  
    D
    FileSets/v3.21/gpio_list
    (12)
  
  
    D
    FileSets/v3.21/main_0units.qml
    (588)
  
  
    D
    FileSets/v3.21/main_1units.qml
    (595)
  
  
    D
    FileSets/v3.21/main_2units.qml
    (602)
  
  
    D
    FileSets/v3.21/relaystate.py
    (110)
  
  
    D
    FileSets/v3.21/serial-starter.rules
    (28)
  
  
    D
    FileSets/v3.21/services.json
    (6593)
  
  
    D
    FileSets/v3.21/services.json.orig
    (6555)
  
  
    D
    FileSets/v3.22/COMPLETE
    (1)
  
  
    D
    FileSets/v3.22/PageSettingsIo.qml
    (92)
  
  
    D
    FileSets/v3.22/PageSettingsIo.qml.orig
    (87)
  
  
    D
    FileSets/v3.22/gpio_list
    (40)
  
  
    D
    FileSets/v3.22/gpio_list.orig
    (8)
  
  
    D
    FileSets/v3.22/relaystate.py
    (123)
  
  
    D
    FileSets/v3.22/relaystate.py.orig
    (106)
  
  
    D
    FileSets/v3.22/serial-starter.rules
    (39)
  
  
    D
    FileSets/v3.22/serial-starter.rules.orig
    (22)
  
  
    D
    FileSets/v3.22/services.json
    (6821)
  
  
    D
    FileSets/v3.22/services.json.orig
    (6555)
  
  
    A
    HelperResources/CommonResources
    (1404)
  
  
    A
    HelperResources/DbusSettingsResources
    (211)
  
  
    A
    HelperResources/EssentialResources
    (79)
  
  
    A
    HelperResources/IncludeHelpers
    (65)
  
  
    A
    HelperResources/LogHandler
    (80)
  
  
    A
    HelperResources/ServiceResources
    (287)
  
  
    A
    HelperResources/VersionResources
    (139)
  
  
    A
    HelperResources/forSetupScript
    (14)
  
  
    A
    HelperResources/version
    (1)
  
  
    M
    gitHubInfo
    (2)
  
  
    M
    setup
    (106)
  


Patch Links:

  https://github.com/Lucifer06/RemoteGPIO/pull/20.patch
  https://github.com/Lucifer06/RemoteGPIO/pull/20.diff

**Comment by thomasinaz41213** [comment]
Yes the new version of setuphelper automatically installs dbus settings as long as the Dbus settings list is present in the package directory, and the appropriate Dbus settings are in that list. Also INSTALL_FILES and ADD_DBUS_SETTINGS must be added after end script at the end of setup.
  

  
These automated functions require the recent version of helper resources, which is called in the beginning of the setup script.   
  

  
I have tested this on fresh firmware for v3.22, and beta v3.30-15, -17, and -18.
  
I am currently in the process of testing older versions. I'll let you know how that goes.
  

  

  

  
  
  
  
  
>

**Comment by thomasinaz41213** [comment]
If you would like to see these changes in action before approving the pull request you can install it by using my repo:
user: thomasinaz41213
package name: RemoteGPIO
branch: beta

**Comment by Lucifer06** [comment]
Will do. Thx looks like you have done a ggod job leveraging all Package Manager capabilities!Excuse possible typo: swallowed by my iPhoneLe 16 mars 2024 à 21:15, thomasinaz41213 ***@***.***> a écrit :﻿
If you would like to see these changes in action before approving the pull request you can install it by using my repo:
user: thomasinaz41213
package name: RemoteGPIO
branch: beta

**Comment by thomasinaz41213** [comment]
I added one more commit to the PR. I had to modify a couple of the patch files so the package is now backward compatible to v2.92. I don't see the need to go back further than that.

**Comment by Lucifer06** [comment]
Merge done!

**Pull request merged**
